In [23]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,ConfusionMatrixDisplay
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import relu,softmax
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping

In [5]:
iris = load_iris()
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df['target'] = iris.target
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                  5.1               3.5                1.4               0.2       0
1                  4.9               3.0                1.4               0.2       0
2                  4.7               3.2                1.3               0.2       0
3                  4.6               3.1                1.5               0.2       0
4                  5.0               3.6                1.4               0.2       0
..                 ...               ...                ...               ...     ...
145                6.7               3.0                5.2               2.3       2
146                6.3               2.5                5.0               1.9       2
147                6.5               3.0                5.2               2.0       2
148                6.2               3.4                5.4               2.3       2
149                5.9               3.0                5.1               1.8       2

[150 rows x 5 columns]

In [11]:
for i in iris.target_names:
    print(i)

setosa
versicolor
virginica

In [13]:
def names(x):
    if x == 0:
        return "setosa"
    if x == 1:
        return "versicolor"
    if x == 2:
        return "virginica"
df['target_names'] = df.target.apply(names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target target_names
0                  5.1               3.5                1.4               0.2       0       setosa
1                  4.9               3.0                1.4               0.2       0       setosa
2                  4.7               3.2                1.3               0.2       0       setosa
3                  4.6               3.1                1.5               0.2       0       setosa
4                  5.0               3.6                1.4               0.2       0       setosa
..                 ...               ...                ...               ...     ...          ...
145                6.7               3.0                5.2               2.3       2    virginica
146                6.3               2.5                5.0               1.9       2    virginica
147                6.5               3.0                5.2               2.0       2    virginica
148                6.2               3.4                5.4               2.3       2    virginica
149                5.9               3.0                5.1               1.8       2    virginica

[150 rows x 6 columns]

In [22]:
x = df.drop(['target','target_names'],axis = 'columns')
y = df['target']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)
mm = MinMaxScaler()
x_train = mm.fit_transform(x_train)
x_test = mm.fit_transform(x_test)
model = Sequential([
    Dense(6,activation = 'relu',input_shape=(4,)),
    Dense(4,activation = 'relu'),
    Dense(2,activation = 'relu'),
    Dense(3,activation = 'softmax')
])

model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)
model.fit(x_train,y_train,epochs = 100,batch_size = 50,validation_split = 0.2)

C:\Users\Shibam\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 4s 2s/step - accuracy: 0.3438 - loss: 1.1079 - val_accuracy: 0.2917 - val_loss: 1.1317
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 289ms/step - accuracy: 0.3438 - loss: 1.1042 - val_accuracy: 0.2917 - val_loss: 1.1294
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - accuracy: 0.3542 - loss: 1.1007 - val_accuracy: 0.2917 - val_loss: 1.1270
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.3542 - loss: 1.0971 - val_accuracy: 0.2917 - val_loss: 1.1243
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.3542 - loss: 1.0942 - val_accuracy: 0.2917 - val_loss: 1.1218
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - accuracy: 0.3958 - loss: 1.0917 - val_accuracy: 0.2917 - val_loss: 1.1197
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - accuracy: 0.4167 - loss: 1.0892 - val_accuracy: 0.2917 - val_loss: 1.1176
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 352ms/step - accuracy: 0.4167 - loss: 1.0873 - val_accuracy: 0.2917 - val_loss: 1.1155
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - accuracy: 0.4062 - loss: 1.0852 - val_accuracy: 0.2917 - val_loss: 1.1139
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.4167 - loss: 1.0833 - val_accuracy: 0.2500 - val_loss: 1.1125
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 516ms/step - accuracy: 0.4375 - loss: 1.0815 - val_accuracy: 0.2500 - val_loss: 1.1115
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - accuracy: 0.4583 - loss: 1.0801 - val_accuracy: 0.2917 - val_loss: 1.1107
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 474ms/step - accuracy: 0.4479 - loss: 1.0791 - val_accuracy: 0.2917 - val_loss: 1.1102
Epoch 14/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 309ms/step - accuracy: 0.4688 - loss: 1.0781 - val_accuracy: 0.2917 - val_loss: 1.1101
Epoch 15/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - accuracy: 0.4792 - loss: 1.0775 - val_accuracy: 0.2917 - val_loss: 1.1102
Epoch 16/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step - accuracy: 0.4792 - loss: 1.0770 - val_accuracy: 0.3333 - val_loss: 1.1102
Epoch 17/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - accuracy: 0.4792 - loss: 1.0762 - val_accuracy: 0.3333 - val_loss: 1.1103
Epoch 18/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - accuracy: 0.4896 - loss: 1.0756 - val_accuracy: 0.3333 - val_loss: 1.1104
Epoch 19/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step - accuracy: 0.5000 - loss: 1.0749 - val_accuracy: 0.3333 - val_loss: 1.1105
Epoch 20/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - accuracy: 0.5000 - loss: 1.0743 - val_accuracy: 0.3333 - val_loss: 1.1108
Epoch 21/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - accuracy: 0.5104 - loss: 1.0735 - val_accuracy: 0.3333 - val_loss: 1.1110
Epoch 22/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 232ms/step - accuracy: 0.5312 - loss: 1.0728 - val_accuracy: 0.3333 - val_loss: 1.1112
Epoch 23/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - accuracy: 0.5312 - loss: 1.0721 - val_accuracy: 0.3333 - val_loss: 1.1112
Epoch 24/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - accuracy: 0.5312 - loss: 1.0713 - val_accuracy: 0.3333 - val_loss: 1.1112
Epoch 25/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 264ms/step - accuracy: 0.5417 - loss: 1.0704 - val_accuracy: 0.3333 - val_loss: 1.1111
Epoch 26/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.5417 - loss: 1.0698 - val_accuracy: 0.3333 - val_loss: 1.1111
Epoch 27/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step - accuracy: 0.5417 - loss: 1.0689 - val_accuracy: 0.3333 - val_loss: 1.1109
Epoch 28/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - accuracy: 0.5417 - loss: 1.0683 - val_accuracy: 0.3333 - val_loss: 1.1107
Epoch 29/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - accuracy: 0.5521 - loss: 1.0674 - val_accuracy: 0.3333 - val_loss: 1.1105
Epoch 30/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 260ms/step - accuracy: 0.5521 - loss: 1.0667 - val_accuracy: 0.3333 - val_loss: 1.1104
Epoch 31/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - accuracy: 0.5625 - loss: 1.0660 - val_accuracy: 0.3750 - val_loss: 1.1103
Epoch 32/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 232ms/step - accuracy: 0.5625 - loss: 1.0651 - val_accuracy: 0.3750 - val_loss: 1.1102
Epoch 33/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 523ms/step - accuracy: 0.5729 - loss: 1.0643 - val_accuracy: 0.3750 - val_loss: 1.1101
Epoch 34/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 357ms/step - accuracy: 0.5938 - loss: 1.0634 - val_accuracy: 0.3750 - val_loss: 1.1100
Epoch 35/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step - accuracy: 0.5938 - loss: 1.0625 - val_accuracy: 0.3750 - val_loss: 1.1099
Epoch 36/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step - accuracy: 0.5938 - loss: 1.0617 - val_accuracy: 0.3750 - val_loss: 1.1099
Epoch 37/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.5938 - loss: 1.0608 - val_accuracy: 0.4167 - val_loss: 1.1097
Epoch 38/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.5938 - loss: 1.0600 - val_accuracy: 0.4167 - val_loss: 1.1096
Epoch 39/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - accuracy: 0.5938 - loss: 1.0591 - val_accuracy: 0.4167 - val_loss: 1.1095
Epoch 40/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - accuracy: 0.5938 - loss: 1.0581 - val_accuracy: 0.4167 - val_loss: 1.1093
Epoch 41/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - accuracy: 0.6042 - loss: 1.0573 - val_accuracy: 0.4167 - val_loss: 1.1093
Epoch 42/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 648ms/step - accuracy: 0.6042 - loss: 1.0563 - val_accuracy: 0.4167 - val_loss: 1.1092
Epoch 43/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - accuracy: 0.6042 - loss: 1.0553 - val_accuracy: 0.4167 - val_loss: 1.1090
Epoch 44/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step - accuracy: 0.6250 - loss: 1.0543 - val_accuracy: 0.4167 - val_loss: 1.1088
Epoch 45/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 585ms/step - accuracy: 0.6250 - loss: 1.0532 - val_accuracy: 0.4167 - val_loss: 1.1087
Epoch 46/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step - accuracy: 0.6354 - loss: 1.0522 - val_accuracy: 0.4167 - val_loss: 1.1085
Epoch 47/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 0.6354 - loss: 1.0511 - val_accuracy: 0.4167 - val_loss: 1.1082
Epoch 48/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - accuracy: 0.6562 - loss: 1.0501 - val_accuracy: 0.4167 - val_loss: 1.1081
Epoch 49/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - accuracy: 0.6667 - loss: 1.0491 - val_accuracy: 0.4167 - val_loss: 1.1080
Epoch 50/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step - accuracy: 0.6667 - loss: 1.0481 - val_accuracy: 0.4167 - val_loss: 1.1078
Epoch 51/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 515ms/step - accuracy: 0.6771 - loss: 1.0470 - val_accuracy: 0.4167 - val_loss: 1.1077
Epoch 52/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 0.6875 - loss: 1.0458 - val_accuracy: 0.4167 - val_loss: 1.1075
Epoch 53/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - accuracy: 0.6875 - loss: 1.0448 - val_accuracy: 0.4167 - val_loss: 1.1072
Epoch 54/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step - accuracy: 0.6875 - loss: 1.0437 - val_accuracy: 0.4583 - val_loss: 1.1070
Epoch 55/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step - accuracy: 0.6875 - loss: 1.0427 - val_accuracy: 0.4583 - val_loss: 1.1070
Epoch 56/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.6875 - loss: 1.0416 - val_accuracy: 0.4583 - val_loss: 1.1069
Epoch 57/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.6875 - loss: 1.0405 - val_accuracy: 0.4583 - val_loss: 1.1068
Epoch 58/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 469ms/step - accuracy: 0.6875 - loss: 1.0393 - val_accuracy: 0.4583 - val_loss: 1.1065
Epoch 59/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 349ms/step - accuracy: 0.6979 - loss: 1.0382 - val_accuracy: 0.4583 - val_loss: 1.1063
Epoch 60/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - accuracy: 0.6979 - loss: 1.0371 - val_accuracy: 0.4583 - val_loss: 1.1062
Epoch 61/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 572ms/step - accuracy: 0.6979 - loss: 1.0360 - val_accuracy: 0.4583 - val_loss: 1.1058
Epoch 62/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - accuracy: 0.6979 - loss: 1.0348 - val_accuracy: 0.4583 - val_loss: 1.1056
Epoch 63/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 488ms/step - accuracy: 0.6979 - loss: 1.0336 - val_accuracy: 0.4583 - val_loss: 1.1053
Epoch 64/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 570ms/step - accuracy: 0.6979 - loss: 1.0324 - val_accuracy: 0.4583 - val_loss: 1.1050
Epoch 65/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 354ms/step - accuracy: 0.6979 - loss: 1.0314 - val_accuracy: 0.4583 - val_loss: 1.1049
Epoch 66/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 373ms/step - accuracy: 0.6979 - loss: 1.0301 - val_accuracy: 0.4583 - val_loss: 1.1046
Epoch 67/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 355ms/step - accuracy: 0.6979 - loss: 1.0289 - val_accuracy: 0.4583 - val_loss: 1.1042
Epoch 68/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 505ms/step - accuracy: 0.7083 - loss: 1.0277 - val_accuracy: 0.4583 - val_loss: 1.1036
Epoch 69/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 399ms/step - accuracy: 0.7083 - loss: 1.0264 - val_accuracy: 0.4583 - val_loss: 1.1030
Epoch 70/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 390ms/step - accuracy: 0.7188 - loss: 1.0252 - val_accuracy: 0.4583 - val_loss: 1.1024
Epoch 71/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 507ms/step - accuracy: 0.7188 - loss: 1.0241 - val_accuracy: 0.4583 - val_loss: 1.1020
Epoch 72/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 202ms/step - accuracy: 0.7188 - loss: 1.0228 - val_accuracy: 0.4583 - val_loss: 1.1017
Epoch 73/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step - accuracy: 0.7188 - loss: 1.0213 - val_accuracy: 0.4583 - val_loss: 1.1009
Epoch 74/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - accuracy: 0.7188 - loss: 1.0201 - val_accuracy: 0.4583 - val_loss: 1.1003
Epoch 75/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step - accuracy: 0.7188 - loss: 1.0189 - val_accuracy: 0.4583 - val_loss: 1.0998
Epoch 76/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 0.7188 - loss: 1.0177 - val_accuracy: 0.4583 - val_loss: 1.0993
Epoch 77/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - accuracy: 0.7188 - loss: 1.0164 - val_accuracy: 0.4583 - val_loss: 1.0989
Epoch 78/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - accuracy: 0.7188 - loss: 1.0151 - val_accuracy: 0.4583 - val_loss: 1.0985
Epoch 79/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 186ms/step - accuracy: 0.7188 - loss: 1.0136 - val_accuracy: 0.4583 - val_loss: 1.0979
Epoch 80/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 353ms/step - accuracy: 0.7188 - loss: 1.0124 - val_accuracy: 0.4583 - val_loss: 1.0976
Epoch 81/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step - accuracy: 0.7188 - loss: 1.0108 - val_accuracy: 0.4583 - val_loss: 1.0970
Epoch 82/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - accuracy: 0.7188 - loss: 1.0094 - val_accuracy: 0.4583 - val_loss: 1.0963
Epoch 83/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 428ms/step - accuracy: 0.7188 - loss: 1.0079 - val_accuracy: 0.4583 - val_loss: 1.0957
Epoch 84/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 532ms/step - accuracy: 0.7188 - loss: 1.0063 - val_accuracy: 0.4583 - val_loss: 1.0949
Epoch 85/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 447ms/step - accuracy: 0.7188 - loss: 1.0048 - val_accuracy: 0.4583 - val_loss: 1.0940
Epoch 86/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 575ms/step - accuracy: 0.7188 - loss: 1.0031 - val_accuracy: 0.4583 - val_loss: 1.0930
Epoch 87/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 634ms/step - accuracy: 0.7188 - loss: 1.0016 - val_accuracy: 0.4583 - val_loss: 1.0918
Epoch 88/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 354ms/step - accuracy: 0.7188 - loss: 0.9998 - val_accuracy: 0.4583 - val_loss: 1.0905
Epoch 89/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - accuracy: 0.7188 - loss: 0.9980 - val_accuracy: 0.4583 - val_loss: 1.0891
Epoch 90/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - accuracy: 0.7188 - loss: 0.9962 - val_accuracy: 0.4583 - val_loss: 1.0875
Epoch 91/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.7188 - loss: 0.9944 - val_accuracy: 0.4583 - val_loss: 1.0860
Epoch 92/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 0.7188 - loss: 0.9926 - val_accuracy: 0.4583 - val_loss: 1.0845
Epoch 93/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step - accuracy: 0.7188 - loss: 0.9906 - val_accuracy: 0.4583 - val_loss: 1.0828
Epoch 94/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step - accuracy: 0.7188 - loss: 0.9887 - val_accuracy: 0.4583 - val_loss: 1.0804
Epoch 95/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 486ms/step - accuracy: 0.7188 - loss: 0.9867 - val_accuracy: 0.4583 - val_loss: 1.0778
Epoch 96/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.7188 - loss: 0.9847 - val_accuracy: 0.4583 - val_loss: 1.0753
Epoch 97/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - accuracy: 0.7188 - loss: 0.9825 - val_accuracy: 0.4583 - val_loss: 1.0728
Epoch 98/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 225ms/step - accuracy: 0.7188 - loss: 0.9803 - val_accuracy: 0.4583 - val_loss: 1.0702
Epoch 99/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - accuracy: 0.7188 - loss: 0.9781 - val_accuracy: 0.4583 - val_loss: 1.0676
Epoch 100/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 318ms/step - accuracy: 0.7188 - loss: 0.9759 - val_accuracy: 0.4583 - val_loss: 1.0647

In [24]:
x = df.drop(['target','target_names'],axis = 'columns')
y = df['target']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.fit_transform(x_test)
model = Sequential([
    Dense(6,activation = 'relu',input_shape=(4,)),
    Dense(4,activation = 'relu'),
    Dense(2,activation = 'relu'),
    Dense(3,activation = 'softmax')
])

model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)
model.fit(x_train,y_train,epochs = 100,batch_size = 33,validation_split = 0.2)

Epoch 1/100

C:\Users\Shibam\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 708ms/step - accuracy: 0.3646 - loss: 1.1057 - val_accuracy: 0.2083 - val_loss: 1.1087
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.3646 - loss: 1.1045 - val_accuracy: 0.2083 - val_loss: 1.1077
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 182ms/step - accuracy: 0.3646 - loss: 1.1032 - val_accuracy: 0.2083 - val_loss: 1.1070
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 0.3646 - loss: 1.1022 - val_accuracy: 0.2083 - val_loss: 1.1062
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.3646 - loss: 1.1013 - val_accuracy: 0.2083 - val_loss: 1.1052
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.3646 - loss: 1.1006 - val_accuracy: 0.2083 - val_loss: 1.1039
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.3646 - loss: 1.0996 - val_accuracy: 0.2083 - val_loss: 1.1035
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.3646 - loss: 1.0990 - val_accuracy: 0.2083 - val_loss: 1.1035
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 218ms/step - accuracy: 0.3646 - loss: 1.0987 - val_accuracy: 0.2083 - val_loss: 1.1035
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 293ms/step - accuracy: 0.3646 - loss: 1.0985 - val_accuracy: 0.2083 - val_loss: 1.1036
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 255ms/step - accuracy: 0.3646 - loss: 1.0982 - val_accuracy: 0.2083 - val_loss: 1.1038
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 300ms/step - accuracy: 0.3646 - loss: 1.0979 - val_accuracy: 0.2083 - val_loss: 1.1041
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 181ms/step - accuracy: 0.3646 - loss: 1.0978 - val_accuracy: 0.2083 - val_loss: 1.1044
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 290ms/step - accuracy: 0.3646 - loss: 1.0976 - val_accuracy: 0.2083 - val_loss: 1.1049
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 166ms/step - accuracy: 0.3646 - loss: 1.0975 - val_accuracy: 0.2083 - val_loss: 1.1054
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.3646 - loss: 1.0972 - val_accuracy: 0.2083 - val_loss: 1.1058
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.3646 - loss: 1.0970 - val_accuracy: 0.2083 - val_loss: 1.1062
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.3646 - loss: 1.0968 - val_accuracy: 0.2083 - val_loss: 1.1066
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.3646 - loss: 1.0967 - val_accuracy: 0.2083 - val_loss: 1.1070
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.3646 - loss: 1.0965 - val_accuracy: 0.2083 - val_loss: 1.1074
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.3646 - loss: 1.0963 - val_accuracy: 0.2083 - val_loss: 1.1078
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3646 - loss: 1.0962 - val_accuracy: 0.2083 - val_loss: 1.1083
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 238ms/step - accuracy: 0.3646 - loss: 1.0961 - val_accuracy: 0.2083 - val_loss: 1.1087
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 289ms/step - accuracy: 0.3646 - loss: 1.0959 - val_accuracy: 0.2083 - val_loss: 1.1090
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 146ms/step - accuracy: 0.3646 - loss: 1.0959 - val_accuracy: 0.2083 - val_loss: 1.1094
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.3646 - loss: 1.0958 - val_accuracy: 0.2083 - val_loss: 1.1098
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.3646 - loss: 1.0957 - val_accuracy: 0.2083 - val_loss: 1.1102
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 189ms/step - accuracy: 0.3646 - loss: 1.0957 - val_accuracy: 0.2083 - val_loss: 1.1106
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.3646 - loss: 1.0956 - val_accuracy: 0.2083 - val_loss: 1.1110
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3646 - loss: 1.0955 - val_accuracy: 0.2083 - val_loss: 1.1114
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.3646 - loss: 1.0954 - val_accuracy: 0.2083 - val_loss: 1.1118
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 312ms/step - accuracy: 0.3646 - loss: 1.0954 - val_accuracy: 0.2083 - val_loss: 1.1122
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.3646 - loss: 1.0953 - val_accuracy: 0.2083 - val_loss: 1.1126
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 0.3646 - loss: 1.0952 - val_accuracy: 0.2083 - val_loss: 1.1130
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.3646 - loss: 1.0951 - val_accuracy: 0.2083 - val_loss: 1.1133
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.3646 - loss: 1.0950 - val_accuracy: 0.2083 - val_loss: 1.1137
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.3646 - loss: 1.0950 - val_accuracy: 0.2083 - val_loss: 1.1140
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 280ms/step - accuracy: 0.3646 - loss: 1.0949 - val_accuracy: 0.2083 - val_loss: 1.1144
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 261ms/step - accuracy: 0.3646 - loss: 1.0949 - val_accuracy: 0.2083 - val_loss: 1.1148
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - accuracy: 0.3646 - loss: 1.0948 - val_accuracy: 0.2083 - val_loss: 1.1152
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.3646 - loss: 1.0947 - val_accuracy: 0.2083 - val_loss: 1.1155
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.3646 - loss: 1.0946 - val_accuracy: 0.2083 - val_loss: 1.1158
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.3646 - loss: 1.0946 - val_accuracy: 0.2083 - val_loss: 1.1162
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.3646 - loss: 1.0946 - val_accuracy: 0.2083 - val_loss: 1.1166
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.3646 - loss: 1.0945 - val_accuracy: 0.2083 - val_loss: 1.1169
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step - accuracy: 0.3646 - loss: 1.0944 - val_accuracy: 0.2083 - val_loss: 1.1173
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 254ms/step - accuracy: 0.3646 - loss: 1.0944 - val_accuracy: 0.2083 - val_loss: 1.1176
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.3646 - loss: 1.0943 - val_accuracy: 0.2083 - val_loss: 1.1181
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.3646 - loss: 1.0943 - val_accuracy: 0.2083 - val_loss: 1.1184
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.3646 - loss: 1.0942 - val_accuracy: 0.2083 - val_loss: 1.1188
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3646 - loss: 1.0941 - val_accuracy: 0.2083 - val_loss: 1.1191
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.3646 - loss: 1.0941 - val_accuracy: 0.2083 - val_loss: 1.1194
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.3646 - loss: 1.0941 - val_accuracy: 0.2083 - val_loss: 1.1197
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 157ms/step - accuracy: 0.3646 - loss: 1.0940 - val_accuracy: 0.2083 - val_loss: 1.1200
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.3646 - loss: 1.0940 - val_accuracy: 0.2083 - val_loss: 1.1204
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 174ms/step - accuracy: 0.3646 - loss: 1.0939 - val_accuracy: 0.2083 - val_loss: 1.1207
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 324ms/step - accuracy: 0.3646 - loss: 1.0939 - val_accuracy: 0.2083 - val_loss: 1.1210
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 169ms/step - accuracy: 0.3646 - loss: 1.0938 - val_accuracy: 0.2083 - val_loss: 1.1214
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.3646 - loss: 1.0938 - val_accuracy: 0.2083 - val_loss: 1.1217
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.3646 - loss: 1.0938 - val_accuracy: 0.2083 - val_loss: 1.1220
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 168ms/step - accuracy: 0.3646 - loss: 1.0938 - val_accuracy: 0.2083 - val_loss: 1.1224
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.3646 - loss: 1.0937 - val_accuracy: 0.2083 - val_loss: 1.1228
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.3646 - loss: 1.0936 - val_accuracy: 0.2083 - val_loss: 1.1230
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.3646 - loss: 1.0936 - val_accuracy: 0.2083 - val_loss: 1.1232
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.3646 - loss: 1.0936 - val_accuracy: 0.2083 - val_loss: 1.1236
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.3646 - loss: 1.0935 - val_accuracy: 0.2083 - val_loss: 1.1238
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.3646 - loss: 1.0935 - val_accuracy: 0.2083 - val_loss: 1.1242
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.3646 - loss: 1.0935 - val_accuracy: 0.2083 - val_loss: 1.1244
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 243ms/step - accuracy: 0.3646 - loss: 1.0935 - val_accuracy: 0.2083 - val_loss: 1.1248
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 201ms/step - accuracy: 0.3646 - loss: 1.0934 - val_accuracy: 0.2083 - val_loss: 1.1251
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 262ms/step - accuracy: 0.3646 - loss: 1.0934 - val_accuracy: 0.2083 - val_loss: 1.1253
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 143ms/step - accuracy: 0.3646 - loss: 1.0934 - val_accuracy: 0.2083 - val_loss: 1.1255
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3646 - loss: 1.0934 - val_accuracy: 0.2083 - val_loss: 1.1258
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.3646 - loss: 1.0933 - val_accuracy: 0.2083 - val_loss: 1.1260
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.3646 - loss: 1.0933 - val_accuracy: 0.2083 - val_loss: 1.1263
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3646 - loss: 1.0932 - val_accuracy: 0.2083 - val_loss: 1.1265
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.3646 - loss: 1.0932 - val_accuracy: 0.2083 - val_loss: 1.1267
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3646 - loss: 1.0932 - val_accuracy: 0.2083 - val_loss: 1.1270
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 194ms/step - accuracy: 0.3646 - loss: 1.0932 - val_accuracy: 0.2083 - val_loss: 1.1272
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.3646 - loss: 1.0932 - val_accuracy: 0.2083 - val_loss: 1.1275
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.3646 - loss: 1.0931 - val_accuracy: 0.2083 - val_loss: 1.1277
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.3646 - loss: 1.0931 - val_accuracy: 0.2083 - val_loss: 1.1279
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 152ms/step - accuracy: 0.3646 - loss: 1.0931 - val_accuracy: 0.2083 - val_loss: 1.1281
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.3646 - loss: 1.0931 - val_accuracy: 0.2083 - val_loss: 1.1284
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.3646 - loss: 1.0931 - val_accuracy: 0.2083 - val_loss: 1.1287
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 258ms/step - accuracy: 0.3646 - loss: 1.0930 - val_accuracy: 0.2083 - val_loss: 1.1289
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3646 - loss: 1.0930 - val_accuracy: 0.2083 - val_loss: 1.1292
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.3646 - loss: 1.0930 - val_accuracy: 0.2083 - val_loss: 1.1294
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 179ms/step - accuracy: 0.3646 - loss: 1.0930 - val_accuracy: 0.2083 - val_loss: 1.1296
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.3646 - loss: 1.0930 - val_accuracy: 0.2083 - val_loss: 1.1299
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 217ms/step - accuracy: 0.3646 - loss: 1.0929 - val_accuracy: 0.2083 - val_loss: 1.1300
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 271ms/step - accuracy: 0.3646 - loss: 1.0929 - val_accuracy: 0.2083 - val_loss: 1.1302
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 148ms/step - accuracy: 0.3646 - loss: 1.0929 - val_accuracy: 0.2083 - val_loss: 1.1305
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.3646 - loss: 1.0929 - val_accuracy: 0.2083 - val_loss: 1.1306
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.3646 - loss: 1.0929 - val_accuracy: 0.2083 - val_loss: 1.1309
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3646 - loss: 1.0928 - val_accuracy: 0.2083 - val_loss: 1.1310
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.3646 - loss: 1.0928 - val_accuracy: 0.2083 - val_loss: 1.1313
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.3646 - loss: 1.0928 - val_accuracy: 0.2083 - val_loss: 1.1314
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.3646 - loss: 1.0928 - val_accuracy: 0.2083 - val_loss: 1.1316
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3646 - loss: 1.0928 - val_accuracy: 0.2083 - val_loss: 1.1318